# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='all_goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('money', '\u793c\u5238'), ('sale', '\u4f18\u60e0\u5238'), ('goods', '\u5b9e\u9645\u5546\u54c1')], max_length=100, verbose_name='\u5546\u54c1\u7c7b\u578b')),
                ('name', models.CharField(max_length=100, verbose_name='\u5546\u54c1\u540d\u79f0')),
                ('ticket', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5238\u53f7\u6216\u4f18\u60e0\u7801')),
                ('code', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5361\u5bc6')),
                ('count', models.IntegerField(blank=True, default=1, null=True, verbose_name='\u6570\u91cf')),
                ('path', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='\u5546\u54c1\u56fe\u7247')),
            ],
            options={
                'verbose_name': '\u5546\u54c1\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='user_draw_prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='\u7528\u6237')),
                ('goods', models.CharField(max_length=250, verbose_name='\u83b7\u5956\u8bb0\u5f55')),
            ],
            options={
                'verbose_name': '\u83b7\u5956\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='user_msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=100, verbose_name='\u8054\u7cfb\u4eba')),
                ('tell', models.CharField(max_length=50, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('address', models.CharField(max_length=250, verbose_name='\u5730\u5740')),
            ],
            options={
                'verbose_name': '\u83b7\u5956\u4eba\u4fe1\u606f',
            },
        ),
    ]
